GitHub Actions CICD Pipeline

diff --git a/.github/workflows/checkov.yml b/.github/workflows/checkov.yml
--- a/.github/workflows/checkov.yml
+++ b/.github/workflows/checkov.yml
@@ -24,85 +24,81 @@ permissions:
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # This workflow contains a single job called "checkov_scan"
-  checkov_scan:
-    # permissions:
-    #   contents: read # for actions/checkout to fetch code
-    #   security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-    #   actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-    name: Run Checkov
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
+  # checkov_scan:
+  #   name: Run Checkov
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
-      - name: Checkout Code
-        uses: actions/checkout@v4
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.13"
+  #     - name: Set up Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: "3.13"
 
-      - name: Install Checkov
-        run: pip install checkov
+  #     - name: Install Checkov
+  #       run: pip install checkov
 
-      - name: Run Checkov
-        run: checkov -d .
+  #     - name: Run Checkov
+  #       run: checkov -d .
 
-      - name: Checkov GitHub Action
-        id: checkov
-        uses: bridgecrewio/checkov-action@master
-        with:
-          # This will add both a CLI output to the console and create a results.sarif file
-          directory: .
-          framework: terraform
-          quiet: true
-          soft_fail: true
-          output_format: cli,sarif
-          output_file_path: console,checkov-scan-results.sarif
-          skip_check: CKV2_GHA_1
-        continue-on-error: true
+  #     - name: Checkov GitHub Action
+  #       id: checkov
+  #       uses: bridgecrewio/checkov-action@master
+  #       with:
+  #         # This will add both a CLI output to the console and create a results.sarif file
+  #         directory: .
+  #         framework: terraform
+  #         quiet: true
+  #         soft_fail: true
+  #         output_format: cli,sarif
+  #         output_file_path: console,checkov-scan-results.sarif
+  #         skip_check: CKV2_GHA_1
+  #       continue-on-error: true
 
-      # - name: Checkov Report
-      #   id: checkov-report
-      #   working-directory: .
-      #   run: |
-      #     while IFS= read -r line; do
-      #     echo "$line" >> $GITHUB_STEP_SUMMARY
-      #     done < results_checkov_failed_only.md
-      # - name: Upload SARIF file
-      #   uses: github/codeql-action/upload-sarif@v3
+  #     # - name: Checkov Report
+  #     #   id: checkov-report
+  #     #   working-directory: .
+  #     #   run: |
+  #     #     while IFS= read -r line; do
+  #     #     echo "$line" >> $GITHUB_STEP_SUMMARY
+  #     #     done < results_checkov_failed_only.md
+  #     # - name: Upload SARIF file
+  #     #   uses: github/codeql-action/upload-sarif@v3
 
-      #   # Results are generated only on a success or failure
-      #   # this is required since GitHub by default won't run the next step
-      #   # when the previous one has failed. Security checks that do not pass will 'fail'.
-      #   # An alternative is to add `continue-on-error: true` to the previous step
-      #   # Or 'soft_fail: true' to checkov.
-      #   if: success() || failure()
-      #   with:
-      #     sarif_file: checkov-scan-results.sarif
+  #     #   # Results are generated only on a success or failure
+  #     #   # this is required since GitHub by default won't run the next step
+  #     #   # when the previous one has failed. Security checks that do not pass will 'fail'.
+  #     #   # An alternative is to add `continue-on-error: true` to the previous step
+  #     #   # Or 'soft_fail: true' to checkov.
+  #     #   if: success() || failure()
+  #     #   with:
+  #     #     sarif_file: checkov-scan-results.sarif
 
-  tflint:
-    name: "Tflint"
-    runs-on: ubuntu-latest
+  # tflint:
+  #   name: "Tflint"
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup TFLint
-        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
-      - name: Install Terraform plugins
-        run: tflint --init
-      - name: Lint Terraform files
-        run: tflint
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Setup TFLint
+  #       run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
+  #     - name: Install Terraform plugins
+  #       run: tflint --init
+  #     - name: Lint Terraform files
+  #       run: tflint
   plan:
     name: "Terraform Plan"
     runs-on: ubuntu-latest
-    needs: [checkov_scan, tflint]
+    # needs: [checkov_scan, tflint]
     defaults:
       run:
         shell: bash
