TF Code Scanning & Analysis with Checkov and GitHub Actions CICD Pipeline

diff --git a/.github/workflows/checkov.yml b/.github/workflows/checkov.yml
--- a/.github/workflows/checkov.yml
+++ b/.github/workflows/checkov.yml
@@ -63,29 +63,43 @@ jobs:
           output_format: cli,sarif
           output_file_path: console,checkov-scan-results.sarif
           skip_check: CKV2_GHA_1
-      - name: Checkov Report
-        id: checkov-report
-        working-directory: .
-        run: |
-          while IFS= read -r line; do
-          echo "$line" >> $GITHUB_STEP_SUMMARY
-          done < results_checkov_failed_only.md
-      - name: Upload SARIF file
-        uses: github/codeql-action/upload-sarif@v3
 
-        # Results are generated only on a success or failure
-        # this is required since GitHub by default won't run the next step
-        # when the previous one has failed. Security checks that do not pass will 'fail'.
-        # An alternative is to add `continue-on-error: true` to the previous step
-        # Or 'soft_fail: true' to checkov.
-        if: success() || failure()
-        with:
-          sarif_file: checkov-scan-results.sarif
+      # - name: Checkov Report
+      #   id: checkov-report
+      #   working-directory: .
+      #   run: |
+      #     while IFS= read -r line; do
+      #     echo "$line" >> $GITHUB_STEP_SUMMARY
+      #     done < results_checkov_failed_only.md
+      # - name: Upload SARIF file
+      #   uses: github/codeql-action/upload-sarif@v3
 
+      #   # Results are generated only on a success or failure
+      #   # this is required since GitHub by default won't run the next step
+      #   # when the previous one has failed. Security checks that do not pass will 'fail'.
+      #   # An alternative is to add `continue-on-error: true` to the previous step
+      #   # Or 'soft_fail: true' to checkov.
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: checkov-scan-results.sarif
+
+  tflint:
+    name: "Tflint"
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup TFLint
+        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
+      - name: Install Terraform plugins
+        run: tflint --init
+      - name: Lint Terraform files
+        run: tflint
   plan:
     name: "Terraform Plan"
     runs-on: ubuntu-latest
-    needs: [checkov_scan]
+    needs: [checkov_scan, tflint]
     defaults:
       run:
         shell: bash
